name: Build SoundKeeper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64

      - name: Build Release x64
        run: msbuild SoundKeeper.sln /m /p:Configuration=Release /p:Platform=x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SoundKeeper64
          path: Bin/SoundKeeper64.exe
